name: Adolfo Bahamonde
description: Portfolio Website
baseurl: # If your site is hosted on a subpath, enter it here
url: # Your full domain or GitHub Pages URL

# Theme settings
theme: jekyll-theme-minimal # You can change this to any Jekyll theme you prefer

# Navigation links
nav_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Author information
author:
  name: Adolfo Bahamonde
  bio: Software Developer and Designer
  location: City, Country
  email: your@email.com
  github_username: your-github-username
  twitter_username: your-twitter-username
  linkedin_username: your-linkedin-username

# Exclude files and directories from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site

# Plugins
plugins:
  - jekyll-seo-tag # You can add more plugins if needed

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
